name: CI
on:
  push:
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'
          cache: 'yarn'
      - name: Yarn version
        run: yarn -v
      - name: Install
        run: yarn install --immutable
      - name: Typecheck
        run: yarn typecheck
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
